services:
  postgres:
    image: postgres:alpine
    container_name: api-nipe-postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: nipe_database
      POSTGRES_USER: nipe_user
      POSTGRES_PASSWORD: nipe_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
